# Generated by Django 6.0.5 on 2026-05-27 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0001_initial'),
        ('onboarding', '0002_paymentsetup_restaurantdocument_staffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('combo_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='onboarding.branch')),
                ('items', models.ManyToManyField(blank=True, related_name='combos', to='menu_management.menuitem')),
            ],
            options={
                'db_table': 'combo_meals',
            },
        ),
        migrations.CreateModel(
            name='BranchMenuPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_prices', to='onboarding.branch')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_prices', to='menu_management.menuitem')),
            ],
            options={
                'db_table': 'branch_menu_prices',
                'unique_together': {('branch', 'menu_item')},
            },
        ),
    ]
